# Site settings
title: MeasureAid 기술 블로그
subtitle: by MeasureAid
email: service@measureaid.com
description: 메져에이드 기술 블로그입니다.
baseurl: ""
url: "http://measureaid.github.com"
paginate: 10
gems: [jekyll-paginate]
subscribe_rss: /atom.xml
exclude: [unused]
author: MeasureAid Service
street_address: 구로구 디지털로 31길 41
city: Seoul
state: Seoul
zip_code: 08375
country: Korea
phone: (02) 702-0201

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: http://github.com/measureaid
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
  style: compressed
